title: "My Static Blog"
description: "A minimal static blog using Markdown and Netlify CMS"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://BoBomar95.github.io/TestBlog" # replace with your GitHub Pages URL
paginate: 0 # Disable pagination to display all posts on the homepage

# Exclude directories and files from processing
exclude:
  - "node_modules"
  - "vendor"

# Optional: Custom collections or other configurations can be added here
