name: Build and Deploy

on:
  push:
    branches: [ main ]
    paths:
      - '_posts/**'
      - 'build.js'
      - 'package.json'
      - 'package-lock.json'
      - 'admin/**'
      - 'styles.css'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Specify the Node.js version you are using

      - name: Install Dependencies
        run: npm install

      - name: Run Build Script
        run: npm run build

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add index.html
          git commit -m "Update index.html via GitHub Actions"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
