name: Build and Deploy

on:
  push:
    branches: [ main ]
    paths:
      - '_posts/**'
      - 'build.js'
      - 'package.json'
      - 'package-lock.json'
      - 'admin/**'
      - 'styles.css'
      - '_config.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Specify the Node.js version you are using

      - name: Install Dependencies
        run: npm install

      # New step to update the pagination setting in _config.yml
      - name: Update Pagination Setting in _config.yml
        run: |
          # If a paginate setting exists, update it to 50; otherwise, add it.
          if grep -q "^paginate:" _config.yml; then
            sed -i 's/^paginate:.*/paginate: 50/' _config.yml
          else
            echo "paginate: 50" >> _config.yml
          fi
          echo "Updated _config.yml content:"
          cat _config.yml

      - name: Run Build Script
        run: npm run build

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add index.html _config.yml
          git commit -m "Update index.html and _config.yml via GitHub Actions" || echo "No changes to commit"
          git push origin main
